import './globals.sass'

import clsx from 'clsx'
import type { Metadata } from 'next'
import { Geist_Mono, Noto_Sans } from 'next/font/google'

import classes from './layout.module.sass'

const geistSans = Noto_Sans({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const classname = clsx(geistSans.variable, geistMono.variable, classes.layout)

  return (
    <>
      <html lang="en">
        <body className={classname}>{children}</body>
      </html>
    </>
  )
}
